---
title: "地理信息系统与R－从地图到地理信息系统"
author: "Miao YU"
date: "2014年12月1日"
output: html_document
---
# 认识地图

[地图](http://zh.wikipedia.org/wiki/地图)说白了就是画满对应现实实体的点、线、面的纸。点线面不用解释，但要想对应现实中的实体，我们需要一些规则。

首先地图要有方向，所以我们应该横纵画上网格，横线表示东西，纵线表示南北，要是不打算指向正东正西可以再画个指南针。但地球是个不怎么圆的球，如果正东正西的去画到平面上就会对实际距离进行拉伸，所以需要设定[投影方式](http://zh.wikipedia.org/wiki/地图投影)。不过我们先不考虑这些麻烦事，先回到天圆地方的时代，假定我们熟悉的[经纬度](http://zh.wikipedia.org/wiki/经纬度)构成的是平面而不是球面，这样随意找张网格纸标上东经多少到多少，北纬多少到多少，就算建立了一个可以对应现实的平面坐标系。为了方便人类阅读，最好画上几厘米，在上面标上实际距离，这样我们这张纸就算可以被识别为地图了。

但地图上不能什么都没有，我们用多边形来表示对应现实实体的区域，例如连接三个不共线的点可以给出一个面，如果这样的面对应了一块草皮，我们就标上草皮。如果标注太不直观，可以直接用颜色来表示，这样再纸上找个角落，把这种对应关系注明就OK了。现在你可以找个GPS，围着学校转个圈，在东西南北角落里标上点，记好经纬度，这样就给出了学校的范围。然后围着学校里的楼去转圈，就给出了楼的范围，回来后按照顺序将学校范围画到坐标纸上，然后再把楼的范围画到学校上，重复这个过程，你就可以得到一张学校的平面示意图，然后加上前面所说的标注就完整了。

好了，现在我们抽象下绘制地图这个过程：一张地图要有坐标，多边形，线，点外带标注就可以了。坐标是一张纸可以称之为地图的关键，地图上的点线面都可以用点及点的连接来表示，标注是方便阅读的。稍微特殊一点的就是经纬度是描述球面坐标的，而我们需要通过投影来在平面上绘制出来，这个过程会造成坐标变弯。

# 从地图到地理信息系统

地图最初的功能就是指路，但指路的本质就是方向加距离加目的地，也就是其实基于方向、距离与目的地的事情我们都应该可以通过地图完成。如果我们为目的地加上各种各样的属性，在我们需要的时候可以方便的提取出来就可以满足更多的需求了。换言之，我们看得到的是方向，距离与点，但点背后要贴一个属性数据库并可以按需提取展示在地图上，这可以算是地理信息系统（GIS）的最初想法。

下面我们看看GIS实际是如何构建的：首先我们得有个GIS软件，一般而言，我们需要先导入带有标注点数据的航拍图，这种图一般会给你上面几个点的经纬度。你对底图标注点进行坐标标注校准后，GIS软件就算是认识这个点了。之后你可以在底图上叠加图层，例如建筑一层，绿化带一层，道路一层，邮筒一层……最后画完了就可以撤掉底图，形成你画的地图。对于建筑，绿化带什么的，你可以多标注些属性，也就是构建与地图的关系数据库。这样你就可以进行信息提取了，例如距离某个点最近的邮局在哪？你不能简单的在两点上划线就完了，你得提取道路图层去计算最近路径，如果考虑交通信息，你得能推荐出不同交通方式到达时间最短的路径。

说了半天，该动手了。这里我们不用专业的GIS软件去实现，太贵。也不用大型互联网公司提供的民用地图网站，太low。作为R大法受害者，我们选择R配合其扩展包来实现地图的绘制。

# 初探R

到[CRAN](http://cran.r-project.org)上去下载对应你操作系统的R，然后打开一个R窗口，因为这是个命令行软件，你大概就看到个大于号。输入下面命令，你应该可以看到一个世界地图。

```{r,message=FALSE}
if(!require('maps')){
    install.packages('maps')
    library('maps')
    }
map()
```

OK，这是个最简单的演示，后面我们先科普下R，然后再用R去构建我们的GIS。要知道我不是GIS专业的，但我常常有画地图，标注及空间统计的需要，如果你也是这个情况，这系列文章更适合你。